### ISSUE TITLE
State did not change to unsafe

### ISSUE THREAD

**Issue by poiromaniax** [amitfin/oref_alert#102]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1407
Downloaded Repositories | 38

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 65.2 GB
disk_used | 20.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | eWeLink Smart Home (1.4.3), Advanced SSH & Web Terminal (19.0.0), Studio Code Server (5.15.0), Nginx Proxy Manager (1.0.1), File editor (5.8.0), Docker Wyze Bridge (2.10.1), Home Assistant Google Drive Backup (0.112.1), Anylist (1.7.2), Whisper (2.1.2), Piper (1.5.2), Govee to MQTT Bridge (2024.07.13-82ddc6e9), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 24
views | 33
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 5, 2024 at 4:43 AM
-- | --
current_recorder_run | September 15, 2024 at 9:39 AM
estimated_db_size | 669.86 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The sensor `binary_sensor_oref_alert` did not change to unsafe for my area:
<img width="1662" alt="image" src="https://github.com/user-attachments/assets/72c97ca0-dfa0-4c1f-b9ac-f488fdbd3c68">
<img width="977" alt="image" src="https://github.com/user-attachments/assets/82721ac4-d30a-423b-986b-0057d7d38636">
<img width="233" alt="image" src="https://github.com/user-attachments/assets/be4f7346-912f-4ece-840f-4d569f079f5a">

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

**Comment by amitfin** [comment]
4 days ago Pikud HaOref changed the list of areas in Israel. The area "מודיעין" was replaced by "מודיעין מכבים רעות":

![image](https://github.com/user-attachments/assets/a14ea17b-7c8b-4cdc-80b5-17fd2554ca90)
https://github.com/amitfin/oref_alert/commit/8c609da3759f9dbe2e26cd7c92e736a531dddf26#diff-498feada52613d24e53ae7f3840c28d14b52338dd9d3acd56c85f8d15fdb6db9

This can also be seen in the above screenshot where the alert was for "מודיעין מכבים רעות" and not for "מודיעין":
![image](https://github.com/user-attachments/assets/0a9885ac-20db-4152-8129-e61edb46afdc)

To fix the definition for your area:
- Make sure the integration version is [v2.12.0](https://github.com/amitfin/oref_alert/releases/tag/v2.12.0) or newer. This is the version with the updated list from Pikud HaOref.
- Reconfigure the integration by removing the old area and choosing the new one:
<img width="380" alt="image" src="https://github.com/user-attachments/assets/c501db5b-7c2a-4084-818e-d661d08a1f72">

I understand it sucks. Such a breaking change should happen with more consideration and careful. However, the list of areas is controlled by Pikud HaOref and all we can do is follow their changes.

**Comment by amitfin** [comment]
[v2.12.2](https://github.com/amitfin/oref_alert/releases/tag/v2.12.2) adds a more proactive approach for this type of issues by raising a repair ticket when an area doesn't exist anymore.
For example, in the above case a repair ticket will be raised explaining that "מודיעין" is an unknown area, it should be removed, and a different relevant area should be selected.

**Comment by poiromaniax** [comment]
@amitfin thank you! I have updated the addon with the correct area.

Thank you for creating (and maintaining!) this addon
