### ISSUE TITLE
Repository amitfin/oref_alert not found

### ISSUE THREAD

**Issue by radinsky** [amitfin/oref_alert#11]
### System Health details

...

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Fail to add the repo in HACS from the button:
![image](https://github.com/amitfin/oref_alert/assets/4540268/131166cf-503a-40c4-a5a6-b4ad7157d658)

Getting:
![image](https://github.com/amitfin/oref_alert/assets/4540268/712a2c95-8dbf-4e0b-a71b-0064071428b8)

![image](https://github.com/amitfin/oref_alert/assets/4540268/c1ce1ade-8137-400b-9b61-9d27ce998fce)

### Reproduction steps

1. Click on: 
![image](https://github.com/amitfin/oref_alert/assets/4540268/131166cf-503a-40c4-a5a6-b4ad7157d658)

2. Follow the flow..

### Debug logs

```text
nothing related
```

**Comment by amitfin** [comment]
Can you provide the following additional information:

- Home Assistant version.
- HACS version.

This is probably a version compatibility issues, as the repository does exist (obviously, as you opened an issue inside it :-) ).

**Comment by amitfin** [comment]
Please use [this page](https://my.home-assistant.io/redirect/system_health) and paste here the data (there is nothing sensitive there).

**Comment by amitfin** [comment]
One more thing to check is the country settings of Home Assistant, which can be found [here](https://my.home-assistant.io/redirect/general/). It should be Israel. It's enforced by HACS (see [this](https://github.com/amitfin/oref_alert/blob/61ef7f4ccf2e9eb5adc6f0a400816b5e7afc82f8/hacs.json#L5)).

**Comment by radinsky** [comment]
> Please use [this page](https://my.home-assistant.io/redirect/system_health). At the bottom of the dialog there is a "copy" button. Use that and paste here the data (there is nothing sensitive there).

## System Information

version | core-2023.10.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 5.10.0-25-amd64
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1340
Downloaded Repositories | 36
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 20, 2023 at 2:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.1
agent_version | 1.2.2
docker_version | 24.0.6
disk_total | 218.1 GB
disk_used | 48.0 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Samba share (10.0.2), Glances (0.19.4), Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), InfluxDB (4.8.0), Grafana (9.1.1), Log Viewer (0.16.0), Studio Code Server (5.13.0), Portainer (2.0.0), Let's Encrypt (4.12.9), ESPHome (2023.10.6), TasmoAdmin (0.25.1), Nginx Proxy Manager (0.12.3), Advanced SSH & Web Terminal (15.1.0), Activity Assistant (v0.0.4.3-alpha), MariaDB (2.6.1), Tailscale (0.13.1), JupyterLab (0.12.1), AdGuard Home (4.8.17), Zigbee2mqtt Edge (edge), MQTT Explorer (browser-1.0.1), Whisper (1.0.0), Piper (1.4.0), Frigate (0.12.1), Mosquitto broker (6.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 31
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 22, 2023 at 8:37 AM
-- | --
current_recorder_run | November 5, 2023 at 12:15 PM
estimated_db_size | 1621.05 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 0 / 0
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by radinsky** [comment]
> One more thing to check is the country settings of Home Assistant, which can be found [here](https://my.home-assistant.io/redirect/general/). It should be Israel. It's enforced by HACS (see [this](https://github.com/amitfin/oref_alert/blob/61ef7f4ccf2e9eb5adc6f0a400816b5e7afc82f8/hacs.json#L5)).
![image](https://github.com/amitfin/oref_alert/assets/4540268/ecf2ecaf-8b70-455a-a7a2-08d0f5117294)

**Comment by amitfin** [comment]
Everything looks good. I don't know what can cause this very simple error. I'll ping you privately so we can debug your system.

**Comment by amitfin** [comment]
One more thing to check:
Go to HACS integration ([here](https://my.home-assistant.io/redirect/integration/?domain=hacs)) and click "Configure" to verify there is no country filter in the configuration:
<kbd>![image](https://github.com/amitfin/oref_alert/assets/19599059/78ea0bc1-9043-4fe5-84fe-04f203ea9f0e)</kbd>

**Comment by radinsky** [comment]
Probably that's it, mine was filtered on US..
