### ISSUE TITLE
Can't setup integration installed through HACS - Error loading shared library libgeos_c

### ISSUE THREAD

**Issue by eytanbiala** [amitfin/oref_alert#26]
## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | armv7l
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4870
Installed Version | 1.34.0
Stage | running
Available Repositories | 1380
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 57.8 GB
disk_used | 6.9 GB
healthy | true
supported | true
board | rpi2
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Mosquitto broker (6.4.0), File editor (5.7.0), Node-RED (17.0.3), Zigbee2MQTT (1.35.1-1), Samba share (12.2.0), Terminal & SSH (9.8.1), Home Assistant Google Drive Backup (0.112.1), AirCast (4.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 9
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 13, 2024 at 4:46 PM
-- | --
current_recorder_run | January 22, 2024 at 12:02 AM
estimated_db_size | 272.39 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After installing the integration through HACS and trying to enable it, the config flow fails to start with this error:
`Config flow could not be loaded: {"message":"Invalid handler specified"}`

Checking the HA logs shows:

```
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 12:04:08 AM (1 occurrences)
Last logged: 12:04:08 AM

Error occurred loading flow for integration oref_alert: Error loading shared library libgeos_c-399df723.so.1.17.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/shapely/lib.cpython-311-arm-linux-musleabihf.so)
```

### Reproduction steps

- Install through HACS
- Attempt to enable integration

### Debug logs

```text
2024-01-21 20:59:15.046 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration oref_alert: Error loading shared library libgeos_c-399df723.so.1.17.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/shapely/lib.cpython-311-arm-linux-musleabihf.so)
```
```


### Diagnostics dump

_No response_

**Comment by amitfin** [comment]
@eytanbiala , did you restart HA after downloading the files through HACS?

https://github.com/amitfin/oref_alert?tab=readme-ov-file#install

> Home Assistant restart is required once the integration files are copied (either by HACS or manually).

**Comment by eytanbiala** [comment]
Yep I did and also tried redownloading and restarting again

**Comment by amitfin** [comment]
Please try the following steps:
1) Remove the integration
2) Restart HA
3) Install the integration
4) Restart HA
At this point the dependencies (including `shapely`) should get installed again. Please check the log if there is an error during the dependencies installation phase.

**Comment by eytanbiala** [comment]
Thanks. I did that, and it took a very long time for the configuration wizard to start but it finally worked!
