### ISSUE TITLE
Multiple sensors

### ISSUE THREAD

**Issue by mbrevda** [amitfin/oref_alert#5]
This is a great initiative - thanks!

It would be great if there can be multiple entries (i.e. multiple sensors) so that different areas can be responded to differently. An example use case might be to flash lights for one area but only have a silent notification for a different area.

**Comment by amitfin** [comment]
@mbrevda please let me know if you need help with your specific configuration, and I'll be happy to help.

**Comment by mbrevda** [comment]
yeah, I guess it's possible that way, too. Thanks and thank you again for making this!
