### ISSUE TITLE
דיליי מרגע האזעקה בפועל לשינוי מצב בהום אססיסטנט

### ISSUE THREAD

**Issue by yanirel** [amitfin/oref_alert#54]
## System Information

version | core-2024.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1409
Downloaded Repositories | 71
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.8 GB
disk_used | 41.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.36.1-1), Terminal & SSH (9.13.0), Samba share (12.3.1), ESPHome (2024.4.0), Cloudflared (5.1.8), Advanced SSH & Web Terminal (17.2.0), eWeLink Smart Home (1.4.3), Piper (1.5.0), Whisper (2.0.0), openWakeWord (1.10.0), MariaDB (2.7.0), Frigate (0.13.2), AppDaemon (0.16.4), ESPresense Companion (0.6.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 49
views | 105
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 30, 2023 at 3:00 AM
-- | --
current_recorder_run | April 18, 2024 at 5:00 AM
estimated_db_size | 5285.40 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.7.0 (c8605e3)
-- | --
cloud_online | 0 / 2
local_online | 1 / 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

שמענו את האזעקה ואז רק אחרי שנכנסו לממד האוטומציה למקרה חירום פעלה (דיליי של 10 שניות בערך)

### Reproduction steps

1.
2.
3.
.

### Debug logs

```text
המקרה קרה ביום של האזעקות בכל הארץ ב2 בלילה...
```

**Comment by amitfin** [comment]
האינטגרציה קוראת את ההתרעות מהאתר של פיקוד העורף כל 2 שניות (כברירת מחדל). תוכל לבדוק מה הערך אצלך במערכת?
אין עוד הרבה שאפשר לעשות. אין איזשהו דיליי מובנה בשאר האינטגרציה. גם אני נתקלתי במקרים שלקח לאתר של פיקוד העורף כמה שניות להתעדכן אחרי שהאזעקה התחילה.

![image](https://github.com/amitfin/oref_alert/assets/19599059/c6bf4bfd-72db-43db-82a9-4b1afae2419a)

**Comment by yanirel** [comment]
הגדרתי על שנייה אחת
